name: Deploy mdBook

on:
  push:
    branches: [main]
    paths:
      - 'wiki/docs/**'
      - 'docs/**'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Convert Obsidian to mdBook
      run: |
        python scripts/obsidian_to_mdbook.py
        
    - name: Build mdBook
      run: mdbook build docs/
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/book 